Update readme and release docs
DataDog/datadog-cloudformation-resources pull request #187
Opened 2021-12-02 22:34 UTC by skarimo

SSIA

2021-12-02 22:52 UTC, ruthnaebeck requested changes
Docs review

2021-12-02 22:52 UTC, ruthnaebeck commented on README.md
> +## Supported Regions
```suggestion
## Supported regions
```

2021-12-02 22:52 UTC, ruthnaebeck commented on README.md
> +*Note*: To privately register a resource in any other region, use the provided packages.
```suggestion
**Note**: To privately register a resource in any other region, use the provided packages.
```

2021-12-02 22:52 UTC, ruthnaebeck commented on RELEASING.md
> +* Check the StackSet in AWS to ensure deploys in all regions succeed
```suggestion
* Check the StackSet in AWS to ensure deploys in all regions succeed.
```

2021-12-03 07:44 UTC, zippolyte commented on RELEASING.md
> +* Run `cfn generate` code based on the project and resource type schema.
Should be done before submit probably

2021-12-03 15:15 UTC, ruthnaebeck approved these changes
👍 for docs

2021-12-03 15:43 UTC, zippolyte approved these changes

2021-12-03 15:49 UTC, merged