Add dashboard resource
DataDog/datadog-cloudformation-resources pull request #93
Opened 2020-10-20 15:29 UTC by zippolyte

SSIA

2020-10-21 19:06 UTC, nmuesch requested changes
Overall looks good. Left some inline comments

2020-10-21 19:06 UTC, nmuesch commented on datadog-dashboards-dashboard-handler/src/datadog_dashboards_dashboard/handlers.py
> +            model.DashboardDefinition = json.dumps(json_dict)
Is it worth catching this too?

2020-10-22 01:22 UTC, nmuesch commented on datadog-dashboards-dashboard-handler/datadog-dashboards-dashboard.json
> +  "description": "Datadog Dashboard",
I'm also trying to standardize adding the version number of the resource in this field (see PR #97) If that gets approved, can we add the version here

2020-10-22 10:31 UTC, zippolyte commented on datadog-dashboards-dashboard-handler/src/datadog_dashboards_dashboard/handlers.py
> +            model.DashboardDefinition = json.dumps(json_dict)
nope, dumping should not raise

2020-10-28 16:05 UTC, nmuesch approved these changes

2020-10-28 16:05 UTC, merged