Update releasing instructions and add version number to resource description
DataDog/datadog-cloudformation-resources pull request #97
Opened 2020-10-21 19:37 UTC by nmuesch

### Requirements for Contributing to this repository

* Fill out the template below. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* The pull request must only fix one issue, or add one feature, at the time.
* The pull request must update the test suite to demonstrate the changed functionality.
* After you create the pull request, all status checks must be pass before a maintainer reviews your contribution. For more details, please see [CONTRIBUTING](/CONTRIBUTING.md).

### What does this PR do?

Update the releasing.md file to note the Java specific release steps (more to come on python specifics later if needed)
Adds the version of the resource to the resource's description as suggested in #87 (Closes #87)

2020-10-22 08:30 UTC, zippolyte requested changes

2020-10-22 08:30 UTC, zippolyte commented on RELEASING.md
> +* (If you're releasing a Java resource) Bump the versions in the pom.xml, e.g. User resource pom.xml
If python, bump in version.py

2020-10-22 16:33 UTC, nmuesch commented on RELEASING.md
> +* (If you're releasing a Java resource) Bump the versions in the pom.xml, e.g. User resource pom.xml
```suggestion
* (If you're releasing a Java resource) Bump the versions in the `pom.xml`, e.g. User resource pom.xml
* (If you're releasing a Python resource) Bump the version in `version.py`
```

2020-10-23 08:23 UTC, zippolyte approved these changes

2020-10-23 20:20 UTC, merged